"""Regenerate fast_logicae/logic_text.c: logic-bert's logic_text.c (logic-bert.tar.gz) with every patch we use,
in order, plus the standalone defaults. The generated file is committed; run this only to rebuild it.

  1 stage2/logicae/transfer_patch.py   --keep-temperature, --load-part codes|gates
  2 stage2/fastlae/global_patch.py     --match 1, --global-every/--global-channels/--global-mean (LTCKP002/LTHRD002)
  3 stage2/logicae/hard_patch.py       --hard-forward (straight-through: forward = the deployed hard network)
  4 stage2/fastlae/fasttrain_patch.py  parallel backward, byte-identical results at any thread count
  4b stage2/fastlae/bitfwd_patch.py    hard forward on packed bits + exact binary-input gradients (byte-identical)
  4c stage2/fastlae/mlmfast_patch.py   masked-word output layer tiled + vectorised, same float ops (byte-identical)
  5 standalone (below)                 `train` trains against the hard network by default (--soft-forward to opt
                                       out), `pretrain` stays soft unless --hard-forward; threads default to all
                                       cores; OMP_WAIT_POLICY=passive unless set (spinning threads cost 5-10x)
usage: python3 make_source.py   (writes logic_text.c next to this file)
"""
import os
import subprocess
import sys
import tarfile
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
S2 = os.path.dirname(HERE)
STANDALONE = [
    ("#include <stdarg.h>\n", "#include <stdarg.h>\n#include <unistd.h>\n"),
    ('        if(!strcmp(key,"--hard-forward")){g_hard_fwd=1;continue;}\n',
     '        if(!strcmp(key,"--hard-forward")){g_fwd_opt=1;continue;}\n'
     '        if(!strcmp(key,"--soft-forward")){g_fwd_opt=0;continue;}\n'),
    ("static int g_hard_fwd=0;  /* --hard-forward: straight-through (hard_patch.py) */",
     "static int g_hard_fwd=0,g_fwd_opt=-1;  /* straight-through (hard_patch.py); g_fwd_opt -1 = train: hard, pretrain: soft */"),
    ('        int stage=!strcmp(cmd,"pretrain");Net *n;',
     '        int stage=!strcmp(cmd,"pretrain");Net *n;\n'
     '        g_hard_fwd=g_fwd_opt>=0?g_fwd_opt:!stage;\n'
     '        fprintf(stderr,"forward: %s\\n",g_hard_fwd?"hard (straight-through: trains the deployed network)":"soft relaxation");'),
    ("    Options o={0};o.c=defaults();o.threads=1;",
     "    Options o={0};o.c=defaults();o.threads=thread_count();"),
    ("int main(int argc,char **argv) {\n",
     "int main(int argc,char **argv) {\n"
     "    if(!getenv(\"OMP_WAIT_POLICY\")){setenv(\"OMP_WAIT_POLICY\",\"passive\",1);execv(\"/proc/self/exe\",argv);}  /* before OpenMP starts */\n"),
    ('         "Commands: selftest | vocab | train | pretrain | export | predict | eval | bench | info");',
     '         "Commands: selftest | vocab | train | pretrain | export | predict | eval | bench | info\\n"\n'
     '         "fast_logicae: train = hard forward (straight-through) by default, --soft-forward to opt out;\\n"\n'
     '         "  pretrain = soft unless --hard-forward; --keep-temperature, --load-part codes|gates,\\n"\n'
     '         "  --match 1, --global-every K --global-channels G --global-mean 1. See README.md.");'),
]


def main():
    tmp = tempfile.mkdtemp()
    with tarfile.open(os.path.join(os.path.dirname(S2), "logic-bert.tar.gz")) as t:
        t.extractall(tmp)
    src = os.path.join(tmp, "logic-bert", "src", "logic_text.c")
    steps = [("logicae/transfer_patch.py", "1.c"), ("fastlae/global_patch.py", "2.c"),
             ("logicae/hard_patch.py", "3.c"), ("fastlae/fasttrain_patch.py", "4.c"), ("fastlae/bitfwd_patch.py", "5.c"),
             ("fastlae/mlmfast_patch.py", "6.c")]
    cur = src
    for script, out in steps:
        nxt = os.path.join(tmp, out)
        subprocess.run([sys.executable, os.path.join(S2, script), cur, nxt], check=True)
        cur = nxt
    s = open(cur).read()
    for a, b in STANDALONE:
        if s.count(a) != 1:
            sys.exit(f"standalone edit: anchor not found exactly once: {a[:70]!r}")
        s = s.replace(a, b)
    s = "/* fast_logicae: GENERATED by make_source.py (logic-bert + transfer, global, hard, fasttrain patches +\n" \
        " * standalone defaults). Edit the patches, not this file. */\n" + s
    open(os.path.join(HERE, "logic_text.c"), "w").write(s)
    print("wrote", os.path.join(HERE, "logic_text.c"))


if __name__ == "__main__":
    main()
